google.maps.__gjsload__('stats', function(_){var xFa=function(a,b){return new _.ZC(a,b)},yFa=function(a){_.F(this,a,2)},zFa=function(a){_.F(this,a,6)},AFa=function(a,b,c,d){var e={};e.host=document.location&&document.location.host||window.location.host;e.v=a.split(".")[1]||a;e.fv=a;e.r=Math.round(1/b);c&&(e.client=c);d&&(e.key=d);return e},CFa=function(a){var b=document;this.token=BFa;this.h=a+"/maps/gen_204";this.g=b},EFa=function(a,b,c){c=c||{};var d=Date.now().toString(36);c.src="apiv3";c.token=a.token;c.ts=d.substr(d.length-6);b.cad=DFa(c);
b=gJ(b,"=","&");b=a.h+"?target=api&"+b;_.Se(new _.Re(a.g),"IMG").src=b;(a=_.C.__gm_captureCSI)&&a(b)},gJ=function(a,b,c){var d=[];_.dl(a,function(e,f){d.push(f+b+e)});return d.join(c)},DFa=function(a){var b={};_.dl(a,function(c,d){b[encodeURIComponent(d)]=encodeURIComponent(c).replace(/%7C/g,"|")});return gJ(b,":",",")},FFa=function(a){if(a instanceof hJ||a instanceof iJ||a instanceof jJ)return a;if("function"==typeof a.next)return new hJ(function(){return a});if("function"==typeof a[_.u(_.x.Symbol,
"iterator")])return new hJ(function(){return a[_.u(_.x.Symbol,"iterator")]()});if("function"==typeof a.Kj)return new hJ(function(){return a.Kj()});throw Error("Not an iterator or iterable.");},hJ=function(a){this.g=a},iJ=function(a){this.g=a},jJ=function(a){hJ.call(this,function(){return a});this.j=a},kJ=function(a,b){this.h={};this.g=[];this.j=this.size=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a)if(a instanceof
kJ)for(c=a.vh(),d=0;d<c.length;d++)this.set(c[d],a.get(c[d]));else for(d in a)this.set(d,a[d])},GFa=function(a,b){return a===b},mJ=function(a){if(a.size!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];lJ(a.h,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.size!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],lJ(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}},lJ=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)},HFa=function(a,b,c,d){var e=_.Ed(_.Mf,0,1);this.o=a;this.D=b;this.m=e;
this.h=c;this.j=d;this.g=new kJ;this.C=Date.now()},nJ=function(a,b,c,d,e){this.C=a;this.D=b;this.o=c;this.j=d;this.m=e;this.h={};this.g=[]},oJ=function(){this.g=_.G(_.Mf,6);this.h=_.G(_.Mf,16);if(_.ki[35]){var a=_.Sd(_.Mf);a=_.G(a,11)}else a=_.js;this.o=new CFa(a);this.D=_.G(_.Td(_.Mf),1);this.F={};this.m={};this.C=_.Ed(_.Mf,0,1);a=this.j=new zFa;var b=_.G(_.Td(_.Mf),1);a.K[1]=b;this.g&&(this.j.K[2]=this.g);this.h&&(this.j.K[3]=this.h)};_.D(yFa,_.E);var pJ;_.D(zFa,_.E);var BFa=Math.round(1E15*Math.random()).toString(36);/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
hJ.prototype.Kj=function(){return new iJ(this.g())};hJ.prototype[_.u(_.x.Symbol,"iterator")]=function(){return new jJ(this.g())};hJ.prototype.h=function(){return new jJ(this.g())};_.B(iJ,_.Ni);iJ.prototype.next=function(){return this.g.next()};iJ.prototype[_.u(_.x.Symbol,"iterator")]=function(){return new jJ(this.g)};iJ.prototype.h=function(){return new jJ(this.g)};_.B(jJ,hJ);jJ.prototype.next=function(){return this.j.next()};_.n=kJ.prototype;_.n.Ce=function(){mJ(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.h[this.g[b]]);return a};_.n.vh=function(){mJ(this);return this.g.concat()};_.n.has=function(a){return lJ(this.h,a)};_.n.equals=function(a,b){if(this===a)return!0;if(this.size!=a.size)return!1;b=b||GFa;mJ(this);for(var c,d=0;c=this.g[d];d++)if(!b(this.get(c),a.get(c)))return!1;return!0};_.n.isEmpty=function(){return 0==this.size};_.n.clear=function(){this.h={};this.j=this.size=this.g.length=0};_.n.remove=function(a){return this.delete(a)};
_.n.delete=function(a){return lJ(this.h,a)?(delete this.h[a],--this.size,this.j++,this.g.length>2*this.size&&mJ(this),!0):!1};_.n.get=function(a,b){return lJ(this.h,a)?this.h[a]:b};_.n.set=function(a,b){lJ(this.h,a)||(this.size+=1,this.g.push(a),this.j++);this.h[a]=b};_.n.forEach=function(a,b){for(var c=this.vh(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};_.n.clone=function(){return new kJ(this)};
_.n.transpose=function(){for(var a=new kJ,b=0;b<this.g.length;b++){var c=this.g[b];a.set(this.h[c],c)}return a};_.n.keys=function(){return FFa(this.Kj(!0)).h()};_.n.values=function(){return FFa(this.Kj(!1)).h()};_.n.entries=function(){var a=this;return xFa(_.u(this,"keys").call(this),function(b){return[b,a.get(b)]})};
_.n.Kj=function(a){mJ(this);var b=0,c=this.j,d=this,e=new _.Ni;e.next=function(){if(c!=d.j)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)return _.ik;var f=d.g[b++];return{value:a?f:d.h[f],done:!1}};return e};HFa.prototype.F=function(a){var b=this;0===this.g.size&&window.setTimeout(function(){var d=AFa(b.D,b.m,b.h,b.j);d.t=Date.now()-b.C;for(var e=b.g,f={},g=_.A(_.u(e,"keys").call(e)),h=g.next();!h.done;h=g.next())h=h.value,f[h]=e.get(h);_.hb(d,f);b.g.clear();EFa(b.o,{ev:"api_maprft"},d)},500);var c=this.g.get(a,0)+1;this.g.set(a,c)};nJ.prototype.F=function(a){this.h[a]||(this.h[a]=!0,this.g.push(a),2>this.g.length&&_.Eu(this,this.H,500))};nJ.prototype.H=function(){for(var a=AFa(this.D,this.o,this.j,this.m),b=0,c;c=this.g[b];++b)a[c]="1";a.hybrid=+_.rm();this.g.length=0;EFa(this.C,{ev:"api_mapft"},a)};oJ.prototype.J=function(a){a=_.ff(a);var b=this.F[a];b||(b=new nJ(this.o,this.D,this.C,this.g,this.h),this.F[a]=b);return b};oJ.prototype.H=function(a){a=_.ff(a);this.m[a]||(this.m[a]=new HFa(this.o,this.D,this.g,this.h));return this.m[a]};
oJ.prototype.M=function(a){if(_.Tf){var b=this.j.clone(),c=Math.floor(Date.now()/1E3);b.K[0]=c;c=new yFa(_.J(b,5));c.K[0]=Math.round(1/this.C);c.K[1]=a;a=this.o;c={ev:"api_map_style"};var d=new _.lh;pJ||(pJ={W:"issssm",fa:["is"]});var e=pJ;b=d.mb(b.toArray(),e);c.pb=encodeURIComponent(b).replace(/%20/g,"+");b=gJ(c,"=","&");_.Se(new _.Re(a.g),"IMG").src=a.h+"?target=api&"+b}};_.Xe("stats",new oJ);});
